name: "build"
on:
  push:
    branches:
#      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_ios:
    name: "Build iOS"
    runs-on: macos-14
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build iOS Simulator app
        run: xcodebuild -workspace iosApp/UiPlayground.xcodeproj/project.xcworkspace -list
#          -configuration Debug -scheme UiPlayground -sdk iphonesimulator