name: "Web"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_web:
    name: "Build Web"
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          lfs: 'true'

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
            add-job-summary-as-pr-comment: 'on-failure'
            build-scan-publish: true
            build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
            build-scan-terms-of-use-agree: 'yes'

      - name: Build Web
        run: ./gradlew :app:wasmJsBrowserDistribution

      - name: Upload build outputs
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'app/build/dist/wasmJs/productionExecutable/*'

    deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
